# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant

name: Java CI

on:
  push:
    branches:
      - master
      - dev/pitc-*
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'zulu'
          java-package: jdk+fx # optional (jdk, jre, jdk+fx or jre+fx) - defaults to jdk
      - name: Build with Ant
        run: ant -noinput -buildfile build.xml build
      - name: Run tests with Ant
        run: ant -noinput -buildfile build.xml test
